#spring:
##  security:
##    user:
##      name: admin
##      password: admin
#  datasource:
#    url: jdbc:postgresql://localhost:5432/learn_spring
#    username: admin
#    password: admin
#    driver-class-name: org.springframework.boot
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/learn_spring
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update


